### ISSUE TITLE
How to set GPU isolation in docker-compose ?

### ISSUE THREAD

**Issue by KerwinSkyRec** [NVIDIA/nvidia-docker#1083]
I'm try to make GPU isolation in docker-compose:

```

version: '3'
services:
  videocvt:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    privileged: true
    volumes:
      - $PWD/../:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=0
    working_dir: /workspace

```

and I can simply type the command below to get only one graphic card's information. :
`
docker run -it -e NVIDIA_VISIBLE_DEVICES=0 env_videocvt nvidia-smi
`

But when i using the `docker-compose` that i just mention, i trying to input the command below to get into bash:
`
docker-compose run --rm --service-ports videocvt bash
`

then i input `nvidia-smi` in conatiner, always get all graphic card information.

Have i done something wrong?
