### ISSUE TITLE
Feature request: use GPU if available, else start container without one

### ISSUE THREAD

**Issue by maxfrei750** [NVIDIA/nvidia-docker#1656]
I'm using `docker compose` to run a container:

```
version: "3.9"
services:
  app:
    image: nvidia/cuda:11.0.3-base-ubuntu20.04
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
```

The container *can* benefit from the presence of a GPU, but it does not strictly need one. Using the above `docker-compose.yaml` results in an error 

> Error response from daemon: could not select device driver "" with capabilities: [[gpu]]

when being used on a machine _without_ a GPU. Is it possible to specify "use a GPU, if one is available, else start the container without one"?
