### ISSUE TITLE
docker runtime更改为nvidia之后创建pod异常

### ISSUE THREAD

**Issue by liufangpeng** [NVIDIA/nvidia-docker#1732]
default Runtime更改为nvidia时的异常

Failed: Error: failed to start container "binpack-2": Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy' nvidia-container-cli: device error: no-gpu-has-128MiB-to-run: unknown device: unknown

当default更改回runc的时候创建pod正常，但是我想实现GPU共享，Runtime要求default为nvidia

**Comment by klueska** [comment]
Can you please show your full command line?

**Comment by liufangpeng** [comment]
apiVersion: apps/v1
kind: Deployment

metadata:
  name: binpack-2
  labels:
    app: binpack-2

spec:
  replicas: 1

  selector: # define how the deployment finds the pods it mangages
    matchLabels:
      app: binpack-2

  template: # define the pods specifications
    metadata:
      labels:
        app: binpack-2

    spec:
      containers:
      - name: binpack-2
        image: harbor.t3caic.com/vgpu/gpu-player:v2
        command: ["/bin/bash", "-ce", "tail -f /dev/null"]
        resources:
          limits:
            aliyun.com/gpu-mem: 125

**Comment by liufangpeng** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: binpack-2
  labels:
    app: binpack-2
spec:
  replicas: 1
  selector: # define how the deployment finds the pods it mangages
    matchLabels:
      app: binpack-2
  template: # define the pods specifications
    metadata:
      labels:
        app: binpack-2
    spec:
      containers:
      - name: binpack-2
        image: harbor.t3caic.com/vgpu/gpu-player:v2
        command: ["/bin/bash", "-ce", "tail -f /dev/null"]
        resources:
          limits:
            aliyun.com/gpu-mem: 125
```
