### ISSUE TITLE
nvidia-docker inside Docker in Docker

### ISSUE THREAD

**Issue by Baschdl** [NVIDIA/nvidia-docker#375]
Is it possible to use nvidia-docker inside [Docker in Docker](https://github.com/jpetazzo/dind)? I tried different configurations but none of them worked. I could share my hacky Dockerfile if you need it.

**Comment by flx42** [comment]
docker-daemon-in-docker? Not docker-client-in-docker, right?

**Comment by Baschdl** [comment]
I guess. My goal is to have multiple containers with access to the GPUs inside one "outer" container with access.

**Comment by flx42** [comment]
It should be possible to make it work, but it's clearly going to be painful since you will need to mount the NVIDIA driver files inside the `docker:dind` container... which actually mean you would need to launch this docker-in-docker container with `nvidia-docker` :)
You're basically on your own here.

**Comment by Max-Pol** [comment]
@Baschdl Did you manage to do it? I'm trying to do the same....

**Comment by Baschdl** [comment]
No, I didn't manage to do it. But good luck with it. 😄

**Comment by perdasilva** [comment]
I managed to get _something_ up in kubernetes - trying using DinD. It's very experimental.

First, I modified the ubuntu-dind image (https://github.com/billyteves/ubuntu-dind) to install nvidia-docker (i.e. added the instructions in the nvidia-docker site to the Dockerfile).

Then I created a pod with two containers, a frontend ubuntu container and the a privileged docker daemon container as a sidecar. The sidecar's image is the modified one I mentioned above. To get everything to work, I also had to mount some of the host node's libraries into the side car.

Here's my pod definition:

```
apiVersion: v1 
kind: Pod 
metadata: 
    name: test-dind 
spec: 
    containers: 
      - name: docker
        image: ubuntu:18.04
        imagePullPolicy: Always
        command: ['sleep', '600'] 
        resources: 
            requests: 
                cpu: 10m 
                memory: 256Mi 
        securityContext: 
            privileged: false
        env: 
          - name: DOCKER_HOST 
            value: tcp://localhost:2375 
      - name: dind-daemon 
        image: perdasilva/ubuntu-dind:16.04
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "2375"
        resources: 
            requests: 
                cpu: 20m 
                memory: 512Mi
                nvidia.com/gpu: 1
            limits:
                nvidia.com/gpu: 1
        securityContext: 
            privileged: true
        volumeMounts: 
          - name: docker-graph-storage 
            mountPath: /var/lib/docker
          - name: libcuda
            mountPath: /usr/lib64/libcuda.so.1
          - name: libnvidia-fatbinaryloader
            mountPath: /usr/lib64/libnvidia-fatbinaryloader.so.396.26
    volumes: 
      - name: docker-graph-storage 
        emptyDir: {}
      - name: libcuda
        hostPath:
          path: /usr/lib64/libcuda.so.1
          type: File
      - name: libnvidia-fatbinaryloader
        hostPath:
          path: /usr/lib64/libnvidia-fatbinaryloader.so.396.26
          type: File
```

You might be able to reproduce this on linux using just docker. I have no idea what the pitfalls or security issues might be here (aside from the privileged container). All I can attest to is that `docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi` worked for me once I got a terminal to the frontend container and installed docker in it.

It would be great to get some feedback from the nvidia experts here what the potential issues with this approach could be.
