### ISSUE TITLE
How to link to nvidia driver library while building image?

### ISSUE THREAD

**Issue by mythly** [NVIDIA/nvidia-docker#405]
I'm trying to compile OpenCV with NVCUVID in nvidia-docker image. The problem is that, `libnvcuvid.so.1` is  part of nvidia driver and only mounted into `/usr/local/nvidia/lib64/` in runtime(`nvidia-docker run ...`). So  OpenCV cannot find NVCUVID library while building image(`docker build ...`).

The trivial solution would be copying those libraries into the image in build-time, but losing the *driver-agnostic* advantages of `nvidia-docker`. Is there any better idea?

**Comment by 3XX0** [comment]
Unfortunately we don't have prebuilt stubs for `libnvcuvid` (see [here](https://github.com/NVIDIA/nvidia-docker/issues/103#issuecomment-223528153)).
You can create a stub library for `libnvcuvid` in your container for linking purposes only. 
`libnvcudvid` doesn't have many symbols so this should be pretty straightforward.

**Comment by flx42** [comment]
For nvcuvid, it looks like the official solution is now to use the files provided with the Video Codec SDK and that will take care of `dlopen`/`dlsym` of the cuvid symbols at runtime. So OpenCV might need to update their code.

**Comment by GudarJs** [comment]
Can you give to me a hint or guide on how to create the libnvcuvid stub library?

**Comment by ZiperRom1** [comment]
Hi, is there a particular thing to do to link `libnvcuvid.so` in a program compiled inside **nvidia-docker** container ?

I'm stuck with a random in error `NvDecoder : cuvidCreateVideoParser(&m_hParser, &videoParserParameters) returned error 1514961680 at /app/NVIDIA_CODEC_SDK/NvDecoder.cu:629` when I'm running the program inside the container.

The program compiles fine in the container and I'm linking `libnvcuvid.so` by copying it with the project source files and add it to container's LD path by doing the following in my

**Dockerfile**

```dockerfile
FROM nvidia/cuda:11.2.1-devel-ubuntu20.04

ENV NVIDIA_DRIVER_CAPABILITIES="all"
ENV TZ="Europe/Paris"
ENV CMAKE_VERSION="3.19.4"
ENV GDB_VERSION="10.1"
ENV LIBUV_VERSION="1.40.0"
ENV GOOGLETEST_VERSION="1.8.1"

# ... several installs ...

# Add lib/stubs from NVIDIA lib to ldconfig for libcuda.so
RUN echo "/usr/local/cuda/targets/x86_64-linux/lib/stubs" >> /etc/ld.so.conf.d/999_cuda-${CUDA_VERSION}.conf && ldconfig

WORKDIR /app

COPY . /app

# Move libnvcuvid.so to /usr/local/lib
RUN cp /app/NVIDIA_CODEC_SDK/lib/libnvcuvid.so /usr/local/lib && ldconfig

# Compile the video extractor
RUN mkdir -p build && cd build && rm -rf * && cmake .. && make -j ${makeCores}
```

**docker-compose.yaml**

```yaml
version: "3.8"

services:
  app:
    image: video-extractor/cuda-11.1:latest
    container_name: video-extractor
    build: .
    runtime: nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "2222:22"       # SSH binding port for host IDE integration
    command: >
      sh -c "service ssh start &&
             tail -f /dev/null"
```

Do you have any idea ?

**Comment by ZiperRom1** [comment]
I'm still struggling with this.

My docker-compose changed a bit with new syntax but the error remains the same:

**docker-compose.yaml**

```
version: "3.9"

services:
  run:
    image: video-extractor/cuda-11.1:latest
    container_name: video-extractor-run
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: /app/build/run /app/resources/videos/720P.mp4
```

**output** of `docker-compose up run`

```
...
video-extractor-run | NvDecoder : cuvidCtxLockCreate(&m_ctxLock, cuContext) returned error 323835680 at /app/NVIDIA_CODEC_SDK/NvDecoder.cu:617
video-extractor-run exited with code 1
```
