### ISSUE TITLE
No process running over GPU in nvidia-smi processes list

### ISSUE THREAD

**Issue by loretoparisi** [NVIDIA/nvidia-docker#476]
I'm running `Theano` within the docker container `nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04` with `libgpuarray` for gpu support.

I get the container up and running and I can see the gpu:

```
# nvidia-smi
Fri Sep 22 12:45:16 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.66                 Driver Version: 384.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   58C    P0    59W / 149W |   1768MiB / 11439MiB |     60%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

I run my container with this `nvidia-docker` configuration in the `docker-compose.yaml` file:

```yaml
networks:
  ai: null
services:
    theano:
    container_name:theano
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    environment:
    - EPOCHS
    entrypoint: bash 
    image: loretoparisi/theano
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 100m
    networks:
    - ai
    ports:
    - 3000:3000
    volumes:
    - fs-17368c5e:/root
    - nvidia_driver_384.66:/usr/local/nvidia:ro
version: '2'
volumes:
  fs-17368c5e:
    driver: efs
  nvidia_driver_384.66:
    external: true
```

While the training seems to work in `theano` and the gpu allocated and used, I cannot see any running process in the gpu processes list within the container:

```
$ docker exec -it theano bash
# nvidia-smi
Fri Sep 22 12:32:53 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.66                 Driver Version: 384.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   58C    P0    59W / 149W |   1768MiB / 11439MiB |     58%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
# exit
exit

```

while if I run `nvidia-smi` in the docker host I can see the process running:

```
$ nvidia-smi
Fri Sep 22 12:32:57 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.66                 Driver Version: 384.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   58C    P0    60W / 149W |   1768MiB / 11439MiB |     61%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     27214    C   python3                                       1757MiB |
+-----------------------------------------------------------------------------+
```

The python script detects the gpu and it seems to use it as well:

```
$ docker exec -it theano bash
# python3 gpu_test.py   
Using cuDNN version 5110 on context None
Mapped name None to device cuda0: Tesla K80 (0000:00:1E.0)
[GpuElemwise{exp,no_inplace}(<GpuArrayType<None>(float64, vector)>), HostFromGpu(gpuarray)(GpuElemwise{exp,no_inplace}.0)]
Looping 1000 times took 0.373223 seconds
Result is [ 1.23178032  1.61879341  1.52278065 ...,  2.20771815  2.29967753
  1.62323285]
Used the gpu
```
